---

- name: Software | Docker | Install package Arch
  pacman:
    name: docker
    state: latest
  when: ansible_distribution == "Archlinux"

- name: Software | Docker | Download script Debian
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: "{{ temp_dir }}/get-docker.sh"
    mode: 0755
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Software | Docker | Install package Debian
  shell: ./get-docker.sh
  args:
    chdir: "{{ temp_dir }}"
    creates: /usr/bin/docker
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Software | Docker | Install package Fedora
  dnf:
    name: docker
    state: latest
  when: ansible_distribution == "Fedora"

- name: Software | Docker | Create group
  group:
    name: docker
    state: present

- name: Software | Docker | Add user to group
  user:
    name: "{{ custom_user }}"
    groups: docker
    append: yes

- name: Software | Docker Compose | Install package
  package:
    name:
      - docker-compose

<<<<<<< HEAD
- name: Software | Utilities | Install pip package
  ansible.builtin.pip:
    name:
      - docker
=======
- name: Software | Docker | Start docker service
  service:
    name: docker
    state: started
    enabled: true
>>>>>>> 92b2eeb (Docker update)
