---

- block:
    - ansible.builtin.include_tasks: software/repositories.yml
    - ansible.builtin.include_tasks: software/tweaks.yml
#    - ansible.builtin.include_tasks: software/packages_utilities.yml

  rescue:
    - ansible.builtin.set_fact: task_failed=true
