---

- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

    # Set up the ansible environment
    - import_tasks: software/packages_docker.yml
    - import_tasks: software/packages_pip.yml
    - import_tasks: software/packages_utilities.yml

  rescue:
    - set_fact: task_failed=true
